# Generated by Django 4.1.2 on 2022-10-21 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_key', models.CharField(max_length=18, null=True)),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='couriers/barcode/image/')),
                ('order_number', models.CharField(max_length=8, null=True)),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('place_from', models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa')], max_length=100, null=True)),
                ('destination', models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa')], max_length=100, null=True)),
                ('number_of_parcel', models.CharField(max_length=100, null=True)),
                ('kgs', models.CharField(max_length=100, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='amount')),
                ('customer_phone', models.CharField(max_length=13, null=True, verbose_name='Customer phone')),
                ('customer_email', models.CharField(max_length=100, null=True, verbose_name='Customer email address')),
                ('date_recieved', models.DateField(blank=True, null=True, verbose_name='Date recieved')),
                ('time_recieved', models.TimeField(blank=True, null=True, verbose_name='Date recieved')),
                ('date_of_stoking_out', models.DateField(blank=True, null=True, verbose_name='Date of stocking out')),
                ('time_of_stoking_out', models.TimeField(blank=True, null=True, verbose_name='Date of stocking out')),
                ('expected_arrival_date', models.DateField(blank=True, null=True, verbose_name='Expected arrival date')),
                ('percel_type', models.CharField(choices=[('normal goods', 'Normal goods'), ('express goods', 'Express goods'), ('sengzen goods', 'Shengzen goods')], max_length=100, null=True, verbose_name='type name')),
                ('status', models.CharField(choices=[('MANIFATED', 'manifested'), ('RCS - recieved from shipper', 'RCS recieved from shipper'), ('OFFLOADED', 'offloaded'), ('DEPARTED', 'departed'), ('ON TRANSIT', 'on transit'), ('ARRIVED', 'arrived'), ('UNDER CLEARANCE', 'under clearance'), ('DELIVERED', 'derivered')], max_length=50, null=True, verbose_name='Courier status')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='package_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_key', models.CharField(max_length=15, null=True)),
                ('mtk', models.CharField(max_length=15, null=True)),
                ('place_from', models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa')], max_length=100, null=True)),
                ('destination', models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa')], max_length=100, null=True)),
                ('master_kgs', models.CharField(max_length=15, null=True)),
                ('kgs', models.CharField(max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('has_dimentions', models.BooleanField(default=0)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('master_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parcels', to='CourierController.package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parcel_insertor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraParcelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MANIFATED', 'manifested'), ('RCS - recieved from shipper', 'RCS recieved from shipper'), ('OFFLOADED', 'offloaded'), ('DEPARTED', 'departed'), ('ON TRANSIT', 'on transit'), ('ARRIVED', 'arrived'), ('UNDER CLEARANCE', 'under clearance'), ('DELIVERED', 'derivered')], max_length=50, null=True, verbose_name='Courier status')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date recieved')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Date recieved')),
                ('terminal', models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa')], max_length=100, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CourierController.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPackageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MANIFATED', 'manifested'), ('RCS - recieved from shipper', 'RCS recieved from shipper'), ('OFFLOADED', 'offloaded'), ('DEPARTED', 'departed'), ('ON TRANSIT', 'on transit'), ('ARRIVED', 'arrived'), ('UNDER CLEARANCE', 'under clearance'), ('DELIVERED', 'derivered')], max_length=50, null=True, verbose_name='Courier status')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date recieved')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Date recieved')),
                ('terminal', models.CharField(choices=[('CAN - Guanzhou', 'CAN - Guanzhou'), ('HKG - HongKong', 'HKG - HongKong'), ('DAR - Dar es salaam', 'DAR - Dar es salaam'), ('DXB - Dubai', 'DXB - Dubai'), ('NBO - Nairobi', 'NBO - Nairobi'), ('SHJ - Sharjah', 'SHJ - Sharjah'), ('JNB - Johanesburg', 'JNB - Johanesburg'), ('MCT - Muscat', 'MCT - Muscat'), ('BOM - Mumbai', 'BOM - Mumbai'), ('ADD - Addis Ababa', 'ADD - Addis Ababa')], max_length=100, null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CourierController.package')),
            ],
        ),
    ]
