# Generated by Django 4.1.2 on 2022-10-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourierController', '0002_alter_extrapackageinfo_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapackageinfo',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='extraparcelinfo',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='extrapackageinfo',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='extrapackageinfo',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
