# Generated by Django 4.0.3 on 2022-10-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourierController', '0004_auto_20221027_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
        migrations.AlterField(
            model_name='extrapackageinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='extraparcelinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
