# Generated by Django 4.0.3 on 2022-10-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourierController', '0005_remove_package_status_alter_extrapackageinfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='has_dimentions',
            field=models.BooleanField(),
        ),
    ]
