# Generated by Django 4.0.3 on 2022-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourierController', '0006_alter_parcel_has_dimentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='has_dimentions',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
