# Generated by Django 4.0.3 on 2022-11-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourierController', '0007_alter_parcel_has_dimentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='parcel/barcode/image/'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='master_barcode',
            field=models.ImageField(blank=True, null=True, upload_to='parcel/master/barcode/image/'),
        ),
    ]
