# Generated by Django 4.1.3 on 2022-11-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourierController', '0008_parcel_barcode_parcel_master_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='percel_type',
            field=models.CharField(choices=[('normal goods', 'Normal goods'), ('express goods', 'Express goods'), ('shengzen goods', 'Shengzen goods')], max_length=100, null=True, verbose_name='parcel type'),
        ),
    ]
