# Generated by Django 4.1.3 on 2022-11-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourierController', '0009_alter_package_percel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrapackageinfo',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='extrapackageinfo',
            name='time',
            field=models.TimeField(auto_now=True, null=True, verbose_name='Time'),
        ),
    ]
