# Generated by Django 4.1.3 on 2022-11-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourierController', '0010_alter_extrapackageinfo_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='length',
        ),
        migrations.AddField(
            model_name='package',
            name='chargable_weight',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='has_dimentions',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='chargable_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='number_of_parcel',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
