# Generated by Django 4.1.3 on 2022-11-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourierController', '0011_remove_parcel_length_package_chargable_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
