# Generated by Django 4.1.3 on 2022-11-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourierController', '0012_package_length_parcel_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='customer_name',
            new_name='reciever_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='package',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='package',
            name='chg_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='custom_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='reciever_address',
            field=models.CharField(max_length=100, null=True, verbose_name='Reciever address'),
        ),
        migrations.AddField(
            model_name='package',
            name='reciever_phone',
            field=models.CharField(max_length=13, null=True, verbose_name='Reciever phone'),
        ),
        migrations.AddField(
            model_name='package',
            name='sender_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='sender_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='chargable_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
